### ISSUE TITLE
Build-Automation einrichten

### ISSUE THREAD

**Issue by forbon** [renao/progress-dashboard-dotnet#6]
Wir brauchen auf jeden Fall buildautomation auf github :-)
Zunächst würde ein einfaches buildscript reichen für die solution.

**Comment by renao** [comment]
Vorschlag zur Vorgehensweise:

Wenn man sich hier mit GitHub Actions eine Pipeline zusammenbaut, purzelt am Ende eine spezifische CI-Datei heraus, bspw. wie hier: https://github.com/renao/sams-wordpress-plugin/blob/master/.github/workflows/php.yml

Das Beispiel zeigt den GitHub-Standard für PHP Composer - sicherlich wird es irgendeinen Standard auch für .NET Core builds, tests und ggf. deploys geben.

Diese Pipelines könnten wir dann ja (je nach interner Deployment-Strategie) zukünftig für GitLab (oder was auch immer) adaptieren.

**Comment by renao** [comment]
Dementsprechend würde ich das Ticket hier ggf. erstmal _nur_ auf GitHub Actions beziehen.

Agree?

**Comment by forbon** [comment]
Durch @renao erledigt
